services:
  wfl-site:
    build:
      context: ..
      dockerfile: zima-deploy/Dockerfile
    container_name: wfl-landing-page
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - wfl-subscribers:/data
volumes:
  wfl-subscribers:
